### ISSUE TITLE
Single Adapter Multiple Deployment Through Versioning

### ISSUE THREAD

**Issue by adozenlines** [mfpdev/mfp-advanced-adapters-samples#6]
Is it possible to do adapter versioning as follows on the same MFP instance?

Live
version 1.0 helloworld adapter is deployed
Testing
version 1.1 helloworld adapter is deployed

Then promote version 1.1 as active

This way 1.0 continues to run without affecting Live / Production use until the next version is promoted.

**Comment by IdanAdar** [comment]
Adapters do not support versioning at this time. You will need to create a copy of the adapter with a different name, or the same name but no have them deployed simultaneously.

**Comment by adozenlines** [comment]
So how about setting up multiple context on the same MFP instance that will run different versions of the adapters through targeted deployments?

**Comment by adozenlines** [comment]
Don't worry I kinda solve the question of deploying the same adapter twice on the same MFP instance without renaming any APIs. Just added a second runtime to the same instance.
